pandorabox/webapp/api_1_0/__init__.py
from flask import Blueprint
api = Blueprint('api', __name__)
from . import machines  # noqa
from . import testcases # noqa
from . import ivtdoc  # noqa

pandorabox/webapp/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views  # noqa

pandorabox/webapp/main/views.py
from flask import render_template
from flask import current_app as cap
from . import main
from config import logger
# ______________________________


@main.route('/', methods=['GET'])
@main.route('/ivts', methods=['GET'])
def ivts():
    return render_template(
        "main/ivts/ivts.html",
        config=cap.config,
    )
# ______________________________


@main.route('/shipped/', methods=['GET'])
def shipped():
    return render_template(
        "main/shipped/shipped.html",
        config=cap.config,
    )
# ______________________________


@main.route('/machines/', methods=['GET'])
def machines():
    template_path = "main/machines/machines.html"
    logger.debug("Template path: %s", template_path)
    return render_template(template_path, config=cap.config)
# ______________________________


@main.route('/testcases/', methods=['GET'])
def testcases():
    return render_template(
        "main/testcases/testcases.html",
        config=cap.config,
    )
# ______________________________

pandorabox/webapp/templates/main/menu.html
<div id="navbar" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">

        <li id="nav-ivthistory">
            <a href="{{ url_for('main.ivts') }}">
                <span class="glyphicon glyphicon-list"></span> Dashboard
            </a>
        </li>

        <li id="nav-shipped">
            <a href="{{ url_for('main.shipped') }}">
                <span class="glyphicon glyphicon-tags"></span> Shipped
            </a>
        </li>

        <li id="nav-machines">
            <a href="{{ url_for('main.machines') }}">
                <span class="glyphicon glyphicon-hdd"></span> Machines
            </a>
        </li>

        <li id="nav-testcases">
            <a href="{{ url_for('main.testcases') }}">
                <span class="glyphicon glyphicon-list-alt"></span> Testcases
            </a>
        </li>

        <li id="nav-test-dashboard">
            <a href="#">
                <span class="glyphicon glyphicon-education"></span> Documentation
            </a>
        </li>
        

        {##% if current_user.is_authenticated %##}
        <li>
            <a href="#">
                Profile
            </a>
        </li>
        {##% endif %##}

    </ul>

    <ul class="nav navbar-nav navbar-right">
        {##% if current_user.is_authenticated %##}
            <li><a href="#">Sign Out</a></li>
        {##% else %##}
            <li><a href="#">Sign In</a></li>
        {##% endif %##}
    </ul>

</div><!--/.nav-collapse -->